config:
  target: "http://localhost:3000"
  phases:
    - duration: 60
      arrivalRate: 5
scenarios:
  - flow:
      - post:
          url: "/whatsapp/send"
          json:
            to: "{{ to }}"
            message: "{{ message }}"
  payload:
    dynamic:
      - function: 'loadPayload'
        module: './loadPayload.js'
